pagina_estatica:
    pattern: /sitio/{pagina}/
    defaults: { _controller: OfertaBundle:Sitio:estatica }

portada:
   pattern: /{ciudad}/
   defaults: { _controller: OfertaBundle:Default:portada, ciudad:  null}
   
_portada:
   pattern: /
   defaults: { _controller: OfertaBundle:Default:portada, ciudad:  null}
  
oferta:
  pattern: /{ciudad}/ofertas/{slug}/
  defaults: { _controller: OfertaBundle:Default:oferta }