security:
  
  firewalls:
    frontend:

      pattern: ^/
      anonymous: ~
      form_login: 
        login_path: usuario_login
        check_path: usuario_login_check
      remember_me:
        key: cupon1234
        lifetime: 3600  
 
  access_control:
    - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/usuario/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/usuario/*, roles: ROLE_USUARIO }
    
  providers:
    usuarios:
      entity: { class: Cupon\UsuarioBundle\Entity\Usuario, property: email }
      
  encoders:
    #Cupon\UsuarioBundle*rio: { algorithm: sha512, iterations: 10 }
    Cupon\UsuarioBundle\Entity\Usuario: plaintext
